// <auto-generated />
namespace MVC_RecursionPermission.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CreateModelNewsCatalogandNews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateModelNewsCatalogandNews));
        
        string IMigrationMetadata.Id
        {
            get { return "202309180607051_Create Model NewsCatalog and News"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
