// <auto-generated />
namespace MVC_RecursionPermission.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CreateModelPermissionController : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateModelPermissionController));
        
        string IMigrationMetadata.Id
        {
            get { return "202309200315121_Create Model Permission Controller"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
